version: '3.8'

services:
  turtlebot3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: public.ecr.aws/yhkim/mosaic/mosaic-turtlebot-ex:latest
    container_name: turtlebot3-controller
    volumes:
      - ./mosaic-config.yaml:/app/mosaic_config.yaml
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    ipc: host
    pid: host
    privileged: true
    restart: unless-stopped
    stdin_open: true
    tty: true
